title: gautam port
email: g@email.com
description: porter cum thinker

logo: logo.svg
bg: bg-img.jpg
avatar: face.jpg

blurb: <p><strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</p>

sass:
  sass_dir: assets/css
  style: :nested